>>> train select 4
>>> train estop
Train 4 Diesel stopped
>>> sun date 10/10/2003
Sunrise: 7:7:0
Sunset: 19:5:3
>>> sun test
Test Reloj Virtual OK
>>> train speed 10
Train 4 Diesel speed set to 10
>>> sleep 5
>>> train speed 15
Train 4 Diesel speed set to 15
>>> sleep 5
>>> train speed 20
Train 4 Diesel speed set to 20
>>> sleep 5
>>> train speed 25
Train 4 Diesel speed set to 25
>>> sleep 5
>>> train speed 28
Train 4 Diesel speed set to 28
>>> sleep 5
>>> train estop
Train 4 Diesel stopped
>>> train speed -10
Train 4 Diesel speed set to -10
>>> sleep 5
>>> train speed -15
Train 4 Diesel speed set to -15
>>> sleep 5
>>> train speed -20
Train 4 Diesel speed set to -20
>>> sleep 5
>>> train speed -25
Train 4 Diesel speed set to -25
>>> sleep 5
>>> train speed -28
Train 4 Diesel speed set to -28
>>> sleep 5
>>> train estop
Train 4 Diesel stopped
>>> sleep 5
>>> 